### ISSUE TITLE
Question about decodeAudioData

### ISSUE THREAD

**Issue by Corginyan** [pixijs/sound#103]
I use some long files as game sountracks. Also i use pixi-loader to load sounds and that returns audio content as `ArrayBuffer`. But as i can see by [specs](https://www.w3.org/TR/webaudio/#AudioBuffer), `AudioBuffer` don't meant to hold audio longer then one minute and specs recommends to use of  `MediaElementAudioSourceNode` for long audio.

And [decodeAudioData](https://github.com/pixijs/pixi-sound/blob/9837a02386d5790f57d06e8dab85db3ec5c74e6d/src/webaudio/WebAudioContext.ts#L336) may take plenty of time on long audio files. And probably can throw unhandled exceptions https://github.com/pixijs/pixi-sound/issues/25, which is can't be catched by `window.onerror` but with `window.onunhandledrejection`.

Also i have some strange debug log from one of users, can't see exact error, because my logger wasn't smart enough to catch it, but i think it's can be related to size of audio file and decode, because there is [null](https://github.com/pixijs/pixi-sound/blob/9f18e27997e5153fe8ef04a36e4489e986b180d9/src/webaudio/WebAudioMedia.ts#L105) instead of `AudioBuffer` in `_source.buffer` of `WebAudioMedia` object, but load was completed successfully and `Sound` object was created.

Steps to reproduce same behaviour:

```javascript
// File exist but contains invalid audio 
let path = 'crapfile.ogg';
PIXI.loader.add(path);
PIXI.loader.onError.add(() => console.log("Loading error"));
PIXI.loader.load((loader, res) => {
    console.log(res[path].sound.duration);
}

window.onerror = function () {
    console.log("There is onerror handler", arguments)
};

window.onunhandledrejection = function () {
    console.log("There is onunhandledrejection handler", arguments)
};
````

**Comment by bigtimebuddy** [comment]
Fixed by #143 , released in v4.0.0
