### ISSUE TITLE
Typescript types incorrect in 2.1.4

### ISSUE THREAD

**Issue by DigitalClouds** [pixijs/sound#111]
The types in the PIXI v4 branch are causing errors when used with the types from @types/pixi.js (4.8.8).

The issue is coming from the interface for `IMediaInstance`, and the event emitter functions, specifically these two:
```typescript
        on(event: string, fn: Function, context?: any): this;
        off(event: string, fn: Function, context?: any, once?: boolean): this;
```

which do not match the ones from the @types/pixi.js definition of an EventEmitter. Changing them to
```typescript
            on(event: string, fn: (...args: any[]) => any, context?: any): this;
            off(event: string, fn: (...args: any[]) => any, context?: any, once?: boolean): this;
```
so they match seems to fix the issue. 

It seems to work in an older version of the pixi.js types, so I'm guessing it's a somewhat recent (although possibly pre-Pixi v5 release) change.

**Comment by bigtimebuddy** [comment]
Want to make a PR against v2.x? I’d be happy to make a release with these typing changes.

**Comment by DigitalClouds** [comment]
Sure, I've started working on that, although it looks like building pixi-sounds fails against that version as well, as `PIXI.loaders.Resource` now declares `url` and `extension` as read only, so `resolveUrl` now throws build errors.

**Comment by spassvogel** [comment]
Is there any update on this?

**Comment by bigtimebuddy** [comment]
Types in PixiJS v6 and this project v4 release now play well with each other. Closing this issue.
