### ISSUE TITLE
Clean up open issues

### ISSUE THREAD

**Issue by laino** [pixijs/sound#121]
I was trying to decide whether to use this library so I looked for open issues related to my use case.

I found some that might potentially prevent me from using it (as is), but they're *old*. 

There are some 2-3 years old issues floating around that are probably not relevant anymore because browsers / this library changed a lot since.

Probably should get cleaned up.

**Comment by bigtimebuddy** [comment]
If anyone wants to help with this project let me know. I’ve mostly been focused on the main pixi project. Could use some help to verify and close issues.
