### ISSUE TITLE
pixi v5.2.1 doesn't work with pixi-sound v3.0.4

### ISSUE THREAD

**Issue by connorjclark** [pixijs/sound#125]
The `pre` and `use` hooks on this plugin are never fired. I noticed that I had two versions of `@pixi/loaders` in my bundle. The latest version was being used by PIXI, but pixi-sound used the other version.

I resolved the issue locally by overriding the version in my package manager (yarn):
```
"resolutions": {
    "pixi-sound/@pixi/loaders": "5.2.1"
  },
```

For a real fix, I think `@pixi/loaders` (and probably all other pixi modules) should be transitive dependencies, with a semver constraint of just the major version. Or, completely remove the dependency all together and require consumers to register the plugin on the Loader.

**Comment by Redmega** [comment]
This is _still_ an issue, for what it's worth. It had me scratching my head for hours today as to why `resource.sound` was undefined

**Comment by bigtimebuddy** [comment]
This has been addressed in this project. `@pixi/loaders` is now a peerDependency. There's larger issue with PixiJS packages that also needs work in this area, see https://github.com/pixijs/pixi.js/discussions/7368
