### ISSUE TITLE
Updates / roadmap?

### ISSUE THREAD

**Issue by Article19** [pixijs/sound#132]
Any planned updates for PIXI Sound that you can share?

**Comment by bigtimebuddy** [comment]
Valid question. I think there are a lot of good ideas in the issues for new features. Such as: more easily able to create groups of sounds, adding filters to sound instances, etc. All that seems doable. The main PixiJS project and being a new dad is stealing most of my time these days. If someone wants to help manage or contribute to this project, would welcome the help!

**Comment by Article19** [comment]
Appreciate the honesty! I'm about to head into a very busy period with a new gig so not the best time to be jumping into an effort like this (also not 100% I have the right skill set) but I am pulling for the continued development and success of this platform.

**Comment by hadimostafapour** [comment]
@bigtimebuddy Not related to topic (sorry) :) but could you publish new changes on npm?

**Comment by bigtimebuddy** [comment]
Sure

**Comment by bigtimebuddy** [comment]
Did a new major version that works with PixiJS v6 and has better types.
Example project here: https://github.com/bigtimebuddy/pixi-sound-webpack-example
