### ISSUE TITLE
Check if sound is played

### ISSUE THREAD

**Issue by creyD** [pixijs/sound#136]
I searched the documentation, but I can't seem to find any method/ state to check if a sound or any sound at all is currently playing. What I would like to do in my case would be to check whether a sound is played and if not, then to play it. And in another case check if any sound is played and then play a specific sound depending on the result.

**Comment by andrewstart** [comment]
Each instance of `Sound` has an `isPlaying` property: https://pixijs.io/pixi-sound/docs/PIXI.sound.Sound.html#isPlaying

**Comment by creyD** [comment]
Thank you for the quick response. I am looking for something a bit more general maybe on the `Pixi.sound` level, so that I don't have to check each and every sound asset in my "library" if it is currently playing.

**Comment by bigtimebuddy** [comment]
You could do something like this.

```js
function isPlayingAny() {
    for (const alias in PIXI.sounds._sounds) {
        if (PIXI.sounds._sounds[alias].isPlaying()) {
            return true;
        }
    }
    return false;
}
```

Seems like a useful feature to add.

**Comment by creyD** [comment]
Thanks for the advice!
