### ISSUE TITLE
PIXI.js v4.4.5 & Sounds v2.1.4 don't work as the PIXI.loaders.Loader is now a getter and not a setter.

### ISSUE THREAD

**Issue by antag0n1st** [pixijs/sound#148]
The sounds ( v2.1.4 ) don't work with PIXI.js 4.4.5
The loader have changed in PIXI.js 4.4.5 so the code breaks.
the PIXI.loaders.Loader is now a getter and not a setter.

![image](https://user-images.githubusercontent.com/1247110/98924840-9288b980-24d5-11eb-8ddf-ff6c6682261d.png)

**Comment by bigtimebuddy** [comment]
Use a more recent build.

**Comment by bigtimebuddy** [comment]
Not planning to support PixiJS v4 anymore, closing this.
