### ISSUE TITLE
Pixi.js@6.0.0 has been released, is this supported?

### ISSUE THREAD

**Issue by famibee** [pixijs/sound#152]
Always I am indebted.
 Pixi.js@6.0.0 has been released, is this supported?
 It seems that a strange error appears.

 thanks you.

　いつもお世話になっております。
　pixi.js@6.0.0がリリースされましたが、こちらは対応されているでしょうか？
　妙なエラーが出るようです。

　ありがとうございます。

pixi-sound.esm.js:14 Uncaught SyntaxError: Unexpected token '!'
    at Object../node_modules/pixi-sound/dist/pixi-sound.esm.js

**Comment by bigtimebuddy** [comment]
This plugin has not been updated to v6 yet, but should be pretty easy to update. Do you have a repo of this happening? Would be helpful to verify.

**Comment by bigtimebuddy** [comment]
Closed with #156
