### ISSUE TITLE
PlayOptions "start" parameter does not work with sound sprites

### ISSUE THREAD

**Issue by qtiki** [pixijs/sound#157]
When playing a sound from a sound sprite using the `sound.play` and providing the `sprite`  name in the `PlayOptions` the `start` parameter is not respected.

I'm not sure whether this should be classified as a bug or as a feature request. It is not stated in the documentation that this would be the case so I would say this is more of a bug than a missing feature.

In any case it would be great if the `start` parameter would be respected. AFAIK this wouldn't require much more than adding the two start parameters together.

**Comment by qtiki** [comment]
I think this would only require changing this: https://github.com/pixijs/sound/blob/07d5ebe07b5888e235544d26ddee9ae266a9e2fa/src/Sound.ts#L605

To something like:
```ts
options.start = sprite.start + (options.start || 0)
```

If that sounds good I can do a PR for this.

**Comment by bigtimebuddy** [comment]
My assumption is that using sprites is a shortcut for start. What use-case do you need sprites but also a custom start point? This could get hairy if you're out of bounds of the sprite you're playing. Also, why not make another sprite if you have a new start point?

**Comment by qtiki** [comment]
I need to pause a song and then on resume I need to rewind it a couple of seconds. Since there is no seek functionality I just restart it with a different start parameter. It works well for a single audio file but when all audio files are bundled in a soundsprite it doesn't.

**Comment by bigtimebuddy** [comment]
Cool, that seems reasonable. If you want to do a PR for this that's good :+1: It might be useful if you could add an out-of-bounds check to make sure that `options.start < options.end`

**Comment by qtiki** [comment]
Sure thing. I'll look into adding tests for the out-of-bounds check too.

**Comment by qtiki** [comment]
So I was looking into adding tests for the out-of-bounds start parameter. I noticed that if you give an out-of-bounds start to a regular sound it will just not play anything and no error is thrown. If we want the functionality to be the same for the sprites I can clamp the calculated start offset to the sprite's end parameter - or would we still rather have an exception thrown for sprites?

**Comment by bigtimebuddy** [comment]
That's a fair question. I realize now that the `console.asserts` are for debugging the dev build (which this project doesn't ship). Maybe it's worth throwing an exception instead? Gotta think on that.

Regardless, we already have an out of bounds assert that should handle this.
https://github.com/pixijs/sound/blob/07d5ebe07b5888e235544d26ddee9ae266a9e2fa/src/webaudio/WebAudioInstance.ts#L301

Go ahead and add the functionality. As long as the documentation is clear about how `start` works with sprite, we should be okay.

**Comment by bigtimebuddy** [comment]
Merged! Thanks for the fix @qtiki
