### ISSUE TITLE
PIXI Sound documentation broken

### ISSUE THREAD

**Issue by oskfan** [pixijs/sound#158]
Hi,

I'm just guessing wildly here, but it seems like the documentation for Pixi Sound at https://pixijs.io/pixi-sound/docs/PIXI.sound.html
is broken since the package name was changed. There is a cached version from April 4th 2021, but the current one seems gone/invalid.

Regards,
Oskar

**Comment by bigtimebuddy** [comment]
New docs are located here: https://pixijs.io/sound/docs/index.html

**Comment by oskfan** [comment]
Thanks alot!
