### ISSUE TITLE
Using pixi.sound with StereoPannerNode

### ISSUE THREAD

**Issue by fraxken** [pixijs/sound#159]
Hello 👋 

I'm working on a class to play sound with a StereoPannerNode to move the sound between left and right (and also fading in/out but this part already work).

I'm totally a newbie with the Web audio API and i'm not sure why my implementation don't work :\ 

The code:
https://github.com/fraxken/pixi-experimental/blob/main/assets/scripts/helpers/spatialSound.js

```js
        /** @type {Sound} */
        this.sound = sound.find(assetName);
        this.sound.volume = this.maxsound;
        this.sound.loop = this.loop;

        // @see https://pixijs.io/sound/docs/Sound.html (context & media)
        /** @type {AudioContext} */
        this.audioCtx = this.sound.context._ctx;
        // console.log(this.audioCtx);

        // @see https://developer.mozilla.org/en-US/docs/Web/API/StereoPannerNode
        this.panNode = this.audioCtx.createStereoPanner();

        this.soundSource = this.sound.media._source;
        // console.log(this.sound.media);
        // console.log(this.soundSource);

        this.soundSource.connect(this.panNode);
        this.panNode.connect(this.audioCtx.destination);

        this.sound.play();
```

My algo also work and my pan is well defined (between 0 to 1 or 0 to -1 depending the position of my character).

```js
this.panNode.pan.value = determinent >= 0 ? pan : -pan;
```

So i suppose i mess something on the configuration ?

Thanks for the time.

**Comment by bigtimebuddy** [comment]
You should probably use the StereoFilter which does this exact thing.

```js
const stereo = new filters.StereoFilter()
this.sound.filters = [stereo];
stereo.pan = -1; // from -1 to 1
```

https://pixijs.io/sound/examples/filters.html
https://pixijs.io/sound/docs/filters.StereoFilter.html

**Comment by fraxken** [comment]
@bigtimebuddy Thanks you i missed this filter!!! It work :)
