### ISSUE TITLE
Adding the package does not work with Yarn

### ISSUE THREAD

**Issue by qtiki** [pixijs/sound#163]
Adding the package to a project using `yarn add @pixi/sound` does not work and results in the following error:

```
>yarn add @pixi/sound
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error @pixi/sound@4.0.2: The engine "yarn" is incompatible with this module. Expected version "please-use-npm". Got "1.22.5"
error Found incompatible module.
```

I would imagine there is no reason why the package would not work with Yarn for the _users_ of the package. I think the point of the engines entry is to ensure that the _developers_ of the package use `npm` instead of `yarn` - which is totally understandable with incompatible lockfiles.

I tried looking for a possible `devEngines` entry but it seems that the npm project has not been very active in adding it even though it has been requested:
- https://github.com/npm/npm/issues/18756
- https://github.com/npm/npm/issues/9765

Unless there is some obscure reason why this package would not work at all with Yarn I would recommend just removing the entry.

**Comment by qtiki** [comment]
One option I just thought of would be to remove the engines entry for `yarn` when publishing. That way anyone cloning the package would need to use `npm` while people installing the published package could use either one.

**Comment by bigtimebuddy** [comment]
Oof, you're right. Sorry about this. Pruning engines from publishing seems like a reasonable workaround.
