### ISSUE TITLE
Example is not clear

### ISSUE THREAD

**Issue by JaLe29** [pixijs/sound#167]
In examples (https://pixijs.io/sound/examples/index.html) there is a code 
```
const sound = PIXI.sound.Sound.from('resources/boing.mp3');
sound.play();
```

Where the hell `PIXI.sound` come from?
```
Property 'sound' does not exist on type 'typeof import("...**/node_modules/pixi.js/index")'.ts(2339)
```

Thank you in advice.

**Comment by bigtimebuddy** [comment]
Those examples are designed if your importing pixi sound using `<script>` on your page. If you're using webpack/parcel or other bundler do something like this:

```js
import { Sound } from '@pixi/sound';
const sound = Sound.from('resources/boing.mp3');
sound.play();
```
