### ISSUE TITLE
Stopping sounds throws an error on old versions of Chrome

### ISSUE THREAD

**Issue by qtiki** [pixijs/sound#169]
We are seeing a bunch of errors coming from `@pixi/sound`:
```
Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
```
As the error suggests these come from all over the audio code where the source node is deinitialized with `this._source.buffer = null`.

I looked at the [specs](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/buffer) for this and assigning `null` should be valid and the node should generate silence. However it seems that Chrome versions 54 to 61 (at least based on our sample) seem to _not_ work according to the specifications. We have over 100k+ events from 3k+ users of this error in our [Sentry](https://sentry.io) tracking so ignoring this is starting to get more and more difficult.

Since most of these assignments are just for cleaning up I was wondering if it would be okay to remove the `buffer` assignments and just set the `_source` to `null`? Or are there some real cases where silence is being generated on purpose?

Or should we try to detect the Chrome version from the user agent and conditionally disable these assignments if they're not supported?

**Comment by bigtimebuddy** [comment]
What about try-catch around the assignment? Either that or removing it seems fine.

**Comment by qtiki** [comment]
I can make a PR to add a try-catch for these and log a warning if it fails.
