### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by WatchaGames** [pixijs/sound#172]
Hi,
Awesome lib thx for this.
I need a non minified version of the lib.
How can I build one ?
Context: I'm fluent in JS but not JS build tools.
Thanks

**Comment by bigtimebuddy** [comment]
Building it is pretty straightforward, but you need to have the repo cloned locally (with `git` or GitHub Desktop) and have node.js/npm installed. One you have those pieces sorted and run `npm install` on the project from the commandline to install all the dependencies, then run this command:

```sh
npm run build
```

This will generate a non-minified version.

**Comment by WatchaGames** [comment]
Thanks great.
Worked.
(i had to install : npm install npm-run-all --save-dev)
Thanks again
