### ISSUE TITLE
SoundLibrary.add should take AudioBuffer as a source

### ISSUE THREAD

**Issue by yueyuzhao** [pixijs/sound#184]
We recently add `AudioBuffer` as a source type for `Sound`, but we can also create `Sound` instances from `SoundLibrary.add`, we need update the signature too.

https://github.com/pixijs/sound/blob/a7f6706b297e94e5b12a2e2d60fcf899026a0f86/src/SoundLibrary.ts#L9

and 

https://github.com/pixijs/sound/blob/a7f6706b297e94e5b12a2e2d60fcf899026a0f86/src/SoundLibrary.ts#L125-L132

and 

https://github.com/pixijs/sound/blob/a7f6706b297e94e5b12a2e2d60fcf899026a0f86/src/SoundLibrary.ts#L145-L150

**Comment by bigtimebuddy** [comment]
Good idea
