### ISSUE TITLE
Play on Sound with unfinished preload leads to an additional preload call ending in a double buffer assignment

### ISSUE THREAD

**Issue by takerukoushirou** [pixijs/sound#206]
I create _Sound_ objects with the `preload` option set to `true` for background music, which calls `Sound._preload()` in the constructor.

On the sound object `play()` is called, which can happen before preload has finished (as can be seen by the returned Promise).
The `Sound.play()` method internally only checks whether the asset is loaded, otherwise will call `Sound._preload()` as well.

This leads to the problem that for the internal _WebAudioMedia_ object `load()` is called again, leading to another XHR for the asset. Eventually the second XHR is finished and an error is thrown due to the second buffer assignment:
`InvalidStateError: The buffer was already set`

_Edit: Formatting._

**Comment by bigtimebuddy** [comment]
Oh good catch! Yeah the play should probably wait for the initial preload instead of kicking off another request.

**Comment by takerukoushirou** [comment]
I ran into this as I wanted to defer loading additional bgm tracks as much as possible, but especially for the first track this ends up in a sequence of creating a _Sound_ object with `preload` property set to `true` and a call to `Sound.play()` pretty much immediately afterwards. At first I thought I oversaw something in the documentation 😄 

To circumvent the issue I now check whether the track media is already loaded and if not defer the `Sound.play()` call to the `loaded` callback.

Some ideas for the fix: Both _IMedia_ implementations seem to be designed for one fixed asset (associated to a single _Sound_ instance) and as such calling `IMedia.load()` more than once could be ignored (leaving the question how to deal with the additional callback) or probably better lead to an error due to invalid usage.
_Sound_ should probably either way check whether media is already loading and skip another load call if it's the case. For that `Sound._preload()` may be the place to check that and skip another media load call, but it should keep track of the additional optional `loaded` callback for consistency.

**Comment by bigtimebuddy** [comment]
Seems like you've already dug into the source on this one. If you want to make a PR, happy to see it. We are doing more work in the PixiJS main project, so I likely won't be able to address this right away.

**Comment by takerukoushirou** [comment]
I can try, will probably take a few days to find some time though, too.
The initial error backtrace was in this case little helpful, so I went through the code when I tried to figure out what's going on.
