### ISSUE TITLE
PixiJS Deprecation Warning: Loader.registerPlugin() is deprecated, use extensions.add() instead. Deprecated since v6.5.0

### ISSUE THREAD

**Issue by anisabboud** [pixijs/sound#210]
Chrome console warning:
```PixiJS Deprecation Warning: Loader.registerPlugin() is deprecated, use extensions.add() instead. Deprecated since v6.5.0```
![image](https://user-images.githubusercontent.com/5672108/184542873-51d2236b-e5b4-44d4-83b8-e810e7c071f5.png)

pixi [sound/src/index.ts](https://github.com/pixijs/sound/blob/main/src/index.ts#L13) calls `Loader.registerPlugin(SoundLoader);`
![image](https://user-images.githubusercontent.com/5672108/184543023-5cf0429a-955d-4d65-8a23-56c309588e54.png)

**Comment by bigtimebuddy** [comment]
I'll be working on an update for this. Thanks for the reminder. Functionally speaking, this is harmless.
