### ISSUE TITLE
Version 5 error

### ISSUE THREAD

**Issue by Omiod** [pixijs/sound#221]
Just upgraded from v4.3.1 to v5 and the web developer console report this, just loading the file:

pixi-sound.js:8 
Uncaught TypeError: Cannot read properties of undefined (reading 'High')
at pixi-sound.js:8:31811
at pixi-sound.js:8:32482

The library is loaded via CDN:
<script src="https://unpkg.com/@pixi/sound/dist/pixi-sound.js" charset="utf-8"></script>

**I just noticed the releases page, ok.
But is there a blog, a new section where breaking changes are announced ?**

**Comment by bigtimebuddy** [comment]
Info is on the releases page, which has the relevant changes. Are you using PixiJS v7?

**Comment by Omiod** [comment]
No I'm on Pixi 6.5.4
I made the error to link to the latest pixi/sound version, without considering that it could have breaking changes.
I'm now specifying the version and looking to upgrade to 7 when out of alpha.
Thank you.
