### ISSUE TITLE
Assets Loader with Sound should use the exact order of the audio formats defined

### ISSUE THREAD

**Issue by vpmedia** [pixijs/sound#223]
I'm trying to load a Sound(Sprite) file using Assets Loader manifest and it always loads the mp3 file and not any of the previous supported formats.

Sample entry:

```
   {
      "name": "sound_kyobi",
      "srcs": "/asset/template/audiosprite/kyobi.{ac3,wav,m4a,ogg,mp3}"
    }
```

Expected behaviour: 
I would expect that the Assets Loader would pick the first supported format in the order I define (like .wav or .mp4)

Current behaviour:
Always the .mp3 format is picked.

Environment: MacOS Monterey 12.6 using latest Safari/Chrome/Firefox browsers. PixiJS 7.0.0-beta.3 with Sound v5.

**Comment by bigtimebuddy** [comment]
Thanks for reporting. I'll look into it.

**Comment by bigtimebuddy** [comment]
The preferred order of file formats is here:

```ts
import { utils } from '@pixi/sound';
utils.extensions;
```

I changed the order from: 
mp3,ogg,oga,opus,mpeg,wav,m4a,aiff,wma,mid,caf
to
ogg,oga,opus,m4a,mp3,mpeg,wav,aiff,wma,mid,caf


If you desire a different order, you can change this array before loading anything. Welcome feedback on the default preference.
