### ISSUE TITLE
Format fallback with different filename bases

### ISSUE THREAD

**Issue by getkey** [pixijs/sound#227]
Format fallbacks are done with a glob syntax, as per #22: `'sounds/music.{mp3,ogg}'`

However, if you are using a module bundler with your audio files, the path of the files will be a hash:

```ts
import musicOpus from 'assets/audio/music.opus'; // becomes /assets/828bfc0f67943dd4405a658c668fdaed.opus
import musicM4a from 'assets/audio/music.m4a'; // becomes /assets/8ed93da17b6a541627629f4c25af3cae.m4a
```

I've tried the following:

```ts
sound.add('music', `{${musicOpus},${musicM4a}}`);
```

But it didn't work, it requested http://localhost:10001/%7Bhttp://localhost:10001/assets/828bfc0f67943dd4405a658c668fdaed.opus,http://localhost:10001/assets/8ed93da17b6a541627629f4c25af3cae.m4a%7D which is obviously a 404.

If it works, the above syntax is okay I suppose, but I'd personally prefer to supply an array, like so:

```ts
sound.add('music', [musicOpus, musicM4a]);
```

**Comment by bigtimebuddy** [comment]
Good suggestion. Thanks @getkey
