### ISSUE TITLE
Sound is suspended while window loses focus

### ISSUE THREAD

**Issue by amiramitai** [pixijs/sound#243]
The following code suspends the audio when the chrome window is blurred.
When switching tab it still works though.
https://github.com/pixijs/sound/blob/19619deb25422ab3bd1f0c8f6022d13e8852b106/src/webaudio/WebAudioContext.ts#L134

I couldn't find a way to disable this programmatically besides monkey patching:
`let origSuspend = sound.webaudio.WebAudioContext.AudioContext.prototype.suspend;
    sound.webaudio.WebAudioContext.AudioContext.prototype.suspend = function() {
        console.log('skipping suspension');
 }`

is there an appropriate way to do this?

**Comment by bigtimebuddy** [comment]
This was added recently in 5.1.1 to prevent sound playing on mobile when app switching or changing browser tabs. You can use 5.1.0 if you do not want suspend behavior, which is probably better than monkey patching.

I think suspend should still be the default behavior, but I can add a flag to opt-out.f

**Comment by amiramitai** [comment]
TBH I rather stick with the latest version. And I also believe that's shouldn't be the default behavior since pixi tickers aren not suspended. With this behavior I either have no legit option to disable this or I should manually add therse event listeners to disable *MY* pixi tickers.

**Comment by bigtimebuddy** [comment]
I don't think the ticker is equivalent, because most browsers already throttle requestAnimationFrame for hidden tabs. Sound is different because is can pollute the user experience for other sites.

**Comment by nicolasalt** [comment]
"a flag to opt-out" that would be perfect, thanks!

**Comment by famibee** [comment]
Change from v4.3.2 to v4.3.3 (I would like to take time to work on v5)

> v4.3.2からv4.3.3への変更の件（作業時間を取ってv5にしたいですが）

I am also having trouble with this behavior on the PC browser version.
"a flag to opt-out", please set it to off.

> 私もPCブラウザ版でこの動作に困っています。
> "a flag to opt-out"、offにする設定を要望します。

**Comment by CyberDex** [comment]
What if we add a 'utils.isMobile.any' check and add a flag to make it work on PC?

Also, then the game works from an iframe, it mutes when the user clicks a page outside of the iframe, which behaves more like a bug...
