### ISSUE TITLE
`disableAutoPause` doesn't disable auto-resume

### ISSUE THREAD

**Issue by ericente** [pixijs/sound#248]
When focus is regained while `disableAutoPause` is true and audio is playing, it seems like the system is still trying to "resume" the already-playing audio, causing a doubling-up of the audio (robotic echoey effect), and loss of ability to control the playback.

**Comment by bigtimebuddy** [comment]
Do you have a repro?

**Comment by ericente** [comment]
Here's an example. Once the demo turns green, click to start sound playing. Click to another window, then back into the green area. Clicking on the background while the frame has focus should start and stop the sound. Not every time, but very often, the audio playback will get a phased/doubled effect, and at this point, the originally-triggered audio will be uncontrollable, and new instances will get toggled on and off.
https://codesandbox.io/s/compassionate-driscoll-lxrptn?file=/src/index.js

**Comment by oskfan** [comment]
+1 on this.

**Comment by bigtimebuddy** [comment]
I published v5.2.1 and v4.4.1 which contain this fix. Let me know if that works for you all.
