### ISSUE TITLE
[bug] HTMLAudioInstance.ts

### ISSUE THREAD

**Issue by twobear** [pixijs/sound#264]
**Bug Description**:

There is a potential writing error in `sound/src/htmlaudio/HTMLAudioInstance.ts` on line 341. 

The code snippet `this.emit('progress', start, this._duration);` should have `'start'` modified to `'start/this._duration'`.

Steps to Reproduce:

Navigate to the sound/src/htmlaudio/HTMLAudioInstance.ts file.
Go to line 341.
Note the mentioned code snippet.
Expected Behavior:

Modify the code to change this.emit('progress', start, this._duration); with start/this._duration to ensure correct behavior.

Thank you for bringing this to attention, looking forward to the resolution of the issue!

**Comment by FerLuisxd** [comment]
Same here.

**Comment by bigtimebuddy** [comment]
Released in v6.0.1
