### ISSUE TITLE
Chrome/Webkit: Sound not playing until click

### ISSUE THREAD

**Issue by TomMettam** [pixijs/sound#84]
I have a Pixi game built into an Angular 7 application, using pixi-sound.

I have a strange issue where after issuing a play() command, as so:

```
sound.play({
    'complete': () => {
        console.log('Complete');
    }
});
```

.. the sound doesn't play, and the 'complete' callback does not fire, **until** I CLICK the webpage. This only seems to happen in Chrome (Blink) and WebKit.  It works just fine in FireFox.

After that initial click, everything works fine and subsequent calls to play() work perfectly.

**Comment by replaysMike** [comment]
I too am seeing this under React.

**Comment by replaysMike** [comment]
I found that setting this fixes it - `PIXI.sound.useLegacy = true;`
It must be called before loading any sound files. I tried to get around this by focusing the canvas, but it only worked a couple times and wasn't reliable.

**Comment by bigtimebuddy** [comment]
This is a limitation of webaudio and the media policies of these browsers. You have to design around it. Please don’t use legacy audio instead as this is much higher latency. Would suggest you create some interactive element to start whatever experience you’re creating.

**Comment by replaysMike** [comment]
This hack seems to actually work:

```
<iframe
  title="audioload"
  src="/assets/game/audio/silence.mp3"
  allow="autoplay"
  id="audio"
  style={{ display: 'none' }}
/>
```

[Silence.mp3](https://github.com/anars/blank-audio/blob/master/250-milliseconds-of-silence.mp3)

**Comment by replaysMike** [comment]
I get why they did it, annoying auto play videos. But I think they overlooked html5 games in this, as I wouldn't be able to do things like intro logos or elements of play before any clicks in the app domain would occur. After all, this is sort of the whole point of Pixi. And in my design, I don't want to annoy users with a clickable element required on load as it would interrupt application flow. But hey, what can you do (other than the above).

**Comment by imokya** [comment]
set PIXI.sound.useLegacy = true throw Excpetion in Chrome console 'Uncaught (in promise) DOMException'
pixi.js v5.03
pixi-sound.js v3.02

**Comment by meanbeanmachine** [comment]
Does anyone have an update for this?  I'm experiencing this as well.  It really messes up the splash/load screen of an html5 game when sounds won't play until the app is clicked on.  I've tried to .focus() everything under the sun with no success.

**Comment by TomMettam** [comment]
@meanbeanmachine It's unfixable without patching the browsers

**Comment by yueyuzhao** [comment]
Hi @meanbeanmachine , it seems that you are developping a hybrid app. If that is the case I think you can :

on iOS (swift):
```swift
// auto play audio or video
if #available(iOS 10.0, *) {
    webview.configuration.mediaTypesRequiringUserActionForPlayback = []
} else {
    // Fallback on earlier versions
    webview.configuration.mediaPlaybackRequiresUserAction = false
}
```

on Android (kotlin):
```kotlin
webView.settings.webview.configuration = false
```

Good luck and happy coding!

**Comment by mon-jai** [comment]
It is a [restriction in the browser's end](https://developer.chrome.com/blog/autoplay/#new-behaviors):

> Chrome's autoplay policies are simple:
> 
> - Muted autoplay is always allowed.
> - Autoplay with sound is allowed if:
>   - The user has interacted with the domain (click, tap, etc.).
>   - On desktop, the user's [Media Engagement Index](https://developer.chrome.com/blog/autoplay/#media-engagement-index) threshold has been crossed, meaning the user has previously played video with sound.
>   - The user has [added the site to their home screen](https://web.dev/customize-install/) on mobile or [installed the PWA](https://web.dev/progressive-web-apps/) on desktop.
> - Top frames can [delegate autoplay permission](https://developer.chrome.com/blog/autoplay/#iframe-delegation) to their iframes to allow autoplay with sound.

**Comment by bigtimebuddy** [comment]
Going to close this, as it's a browser limitation.
